=== Kaehl1/ProyectoXML/GreenProtocol.dtd
<!ELEMENT perfil (usuario,juego)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT juego (partidas,logros)>
<!ATTLIST juego nombre CDATA #REQUIRED>
<!ELEMENT partidas (partida+)>
<!ELEMENT partida (clase,jefe,puntos)>
<!ATTLIST partida id CDATA #REQUIRED>
<!ELEMENT clase (#PCDATA)>
<!ELEMENT jefe (nombre,clase)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>
<!ELEMENT logros (logro+)>
<!ELEMENT logro (nombre,descripcion)>
<!ATTLIST logro puntos (10|15|25|5) #REQUIRED>
<!ATTLIST logro completado (no|si) #REQUIRED>
<!ATTLIST logro secreto (no|si) #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>

=== Kaehl1/ProyectoXML/GreenProtocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="GreenProtocol.xsl" type="text/xsl"?>
<!DOCTYPE perfil SYSTEM "GreenProtocol.dtd">
<perfil>
    <usuario>Kaehl</usuario>
    <juego nombre="Green Protocol">
        <partidas>
            <partida id="001">
                <clase>Guerrero</clase>
                <jefe>
                    <nombre>Vaarun</nombre>
                    <clase>Paladín</clase>
                </jefe>
                <puntos>17</puntos>
            </partida>
            <partida id="002">
                <clase>Pícaro</clase>
                <jefe>
                    <nombre>Galactius</nombre>
                    <clase>Guerrero</clase>
                </jefe>
                <puntos>0</puntos>
            </partida>
            <partida id="003">
                <clase>Pícaro</clase>
                <jefe>
                    <nombre>Horacio</nombre>
                    <clase>Paladín</clase>
                </jefe>
                <puntos>24</puntos>
            </partida>
            <partida id="004">
                <clase>Paladin</clase>
                <jefe>
                    <nombre>Gregorio</nombre>
                    <clase>Guerrero</clase>
                </jefe>
                <puntos>0</puntos>
            </partida>
        </partidas>
        <logros>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>Alcóholico</nombre>
                <descripcion>Has consumido una poción</descripcion>
            </logro>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>¿Y este botón que hace?</nombre>
                <descripcion>Has utilizado tu habilidad especial</descripcion>
            </logro>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>La primera regla</nombre>
                <descripcion>Has jugado tu primera partida</descripcion>
            </logro>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>Bautismo de acero</nombre>
                <descripcion>Has jugado una partida siendo Guerrero</descripcion>
            </logro>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>Cruzada personal</nombre>
                <descripcion>Has jugado una partida siendo Paladin</descripcion>
            </logro>
            <logro puntos="5" completado="si" secreto="no">
                <nombre>Presentación de credenciales</nombre>
                <descripcion>Has jugado una partida siendo Pícaro</descripcion>
            </logro>
            <logro puntos="10" completado="si" secreto="no">
                <nombre>Dominio del ring</nombre>
                <descripcion>Has ganado tu primera partida</descripcion>
            </logro>
            <logro puntos="10" completado="si" secreto="no">
                <nombre>La senda de la espada</nombre>
                <descripcion>Has ganado tu primera partida siendo Guerrero</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Caminante del sol</nombre>
                <descripcion>Has ganado tu primera partida siendo Paladín</descripcion>
            </logro>
            <logro puntos="10" completado="si" secreto="no">
                <nombre>Veneno en las venas</nombre>
                <descripcion>Has ganado tu primera partida siendo Pícaro</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Chatarra</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Guerrero</descripcion>
            </logro>
            <logro puntos="10" completado="si" secreto="no">
                <nombre>Hereje</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Paladín</descripcion>
            </logro>
            <logro puntos="10" completado="no" secreto="no">
                <nombre>Caza-ratas</nombre>
                <descripcion>Has ganado tu primera partida a un jefe Pícaro</descripcion>
            </logro>
            <logro puntos="15" completado="si" secreto="no">
                <nombre>Bajo control</nombre>
                <descripcion>Ganar una partida con 10HP o menos</descripcion>
            </logro>
            <logro puntos="15" completado="no" secreto="no">
                <nombre>Depredador Herido</nombre>
                <descripcion>Ganar una partida con 65HP o más</descripcion>
            </logro>
            <logro puntos="25" completado="si" secreto="si">
                <nombre>Freno facial</nombre>
                <descripcion>Has chocado contra un muro</descripcion>
            </logro>
            <logro puntos="25" completado="no" secreto="si">
                <nombre>Fantasma del ring</nombre>
                <descripcion>Has ganado una partida sin recibir daño</descripcion>
            </logro>
        </logros>
    </juego>
</perfil>
